### ISSUE TITLE
Using node.js

### ISSUE THREAD

**Issue by Jack-O-Brian** [Ciaxur/RESTful-Notify.api#1]
Bro

**Comment by Ciaxur** [comment]
@HawaiinPizza What do you suggest using? 😂

**Comment by Jack-O-Brian** [comment]
On Sat, Mar 13, 2021 at 08:05:34AM -0800, Omar² wrote:
> @HawaiinPizza What do you suggest using? 😂
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Ciaxur/RESTful-Notify.api/issues/1#issuecomment-798560169
Use C or Lisp

**Comment by Ciaxur** [comment]
Could be a cool separate project idea to learn the lower-level systems that go into play :thinking:.
